project_id = "ublbxvpmoccmegtwaslh"

[functions.generate-blog-post]
verify_jwt = false

[functions.suggest-blog-topics]
verify_jwt = false

[functions.generate-recipe]
verify_jwt = false

[functions.auto-blog-post]
verify_jwt = false
